name: gcloud auth test
on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - run: echo $GCP_SERVICE_ACCOUNT | base64 -di > ~/service_account_key.json
      - run: curl https://sdk.cloud.google.com | bash -y \
             source .bash_profile \
             gcloud version \
             gcloud auth activate-service-account \
             cloud-storage-transfer-bot@voltaic-country-281210.iam.gserviceaccount.com \
             --key-file /service_account_key.json \
             --project voltaic-country-281210
      - run: gcloud auth list
             
      
